import LegalDoc, { LegalSection } from '../../../components/ui/LegalDoc';
import FooterMini from '../../../components/ui/FooterMini';

export const metadata = { title: 'Privacy Policy' };

export default function PrivacyPage() {
  return (
    <>
      <LegalDoc
        eyebrow="PRIVACY POLICY"
        title="What Xavier sees, and what it does with it."
        updated="August 23, 2026"
        appliesTo="Applies to all SlovX accounts and their connected leads/customers"
        intro={<>
          This Privacy Policy explains how SlovX ("we," "us," "our") collects, uses, stores, and shares information
          in connection with the SlovX platform and its autonomous AI agent, Xavier (the "Service"). It applies both
          to our direct customers ("Customer," "you") and, where relevant, to the end-customers/leads ("Lead," "End-User")
          who message a business's Xavier-powered WhatsApp number.
        </>}
        disclaimer="This document is a general-purpose template and does not constitute legal advice. Bracketed fields must be completed, and this Policy should be reviewed by a qualified lawyer familiar with your operating jurisdiction (e.g. GDPR, CCPA, or other applicable data-protection frameworks) before publication."
      >
        <LegalSection number={1} title="Information We Collect">
          <p>We collect the following categories of information:</p>
          <ul className="list-disc list-outside ml-5 space-y-2">
            <li><strong className="text-white/85">Account information:</strong> business name, owner name, email, phone number, billing details, and Company Configuration (products, pricing, policies) you provide.</li>
            <li><strong className="text-white/85">Conversation data:</strong> messages exchanged between Leads and Xavier via WhatsApp (and any additional connected channels), including text and voice-note transcriptions where that feature is used.</li>
            <li><strong className="text-white/85">Derived data:</strong> qualification stage, sentiment/intent scores, and enrichment attributes (e.g. estimated company size or revenue tier) generated by the Service to route conversations appropriately.</li>
            <li><strong className="text-white/85">Technical data:</strong> IP address, device/browser metadata, and usage logs collected automatically for security, debugging, and service-reliability purposes.</li>
            <li><strong className="text-white/85">Third-party platform data:</strong> information received via connected integrations (WhatsApp Business/Meta, Google Calendar, Google Sheets, CRM systems) as authorized by you.</li>
          </ul>
        </LegalSection>

        <LegalSection number={2} title="How We Use Information">
          <p>Collected information is used to:</p>
          <ul className="list-disc list-outside ml-5 space-y-2">
            <li>Operate the Service — generating conversational responses, qualifying leads, scheduling meetings, and syncing data to your connected tools.</li>
            <li>Maintain conversation continuity across sessions (so Xavier can reference earlier context within an ongoing lead relationship).</li>
            <li>Monitor and improve service reliability, including automated error monitoring and abuse/rate-limit detection.</li>
            <li>Communicate with you regarding your account, billing, or material changes to the Service.</li>
            <li>Comply with legal obligations and enforce our Terms & Conditions.</li>
          </ul>
        </LegalSection>

        <LegalSection number={3} title="AI Processing Disclosure">
          <p>
            Conversation text is processed by third-party large language model providers (such as Anthropic) to generate
            Xavier's responses, and may be processed by third-party transcription or embedding providers where voice-note
            transcription or semantic caching features are enabled. These providers process data under their own applicable
            data-processing terms. We select providers that offer contractual data-handling commitments, but we do not
            control their infrastructure directly.
          </p>
        </LegalSection>

        <LegalSection number={4} title="Data Retention">
          <p>
            Conversation and account data is retained for as long as your account is active, and for a limited period afterward
            as reasonably necessary for legal, billing, or dispute-resolution purposes. You may request deletion of your account
            data as described in Section 8, subject to any retention obligations imposed by applicable law or active integrations
            (e.g. records already synced to your own CRM).
          </p>
        </LegalSection>

        <LegalSection number={5} title="Data Sharing">
          <p>We do not sell personal information. We share data only in the following circumstances:</p>
          <ul className="list-disc list-outside ml-5 space-y-2">
            <li><strong className="text-white/85">Payment processing:</strong> billing name, email, and payment details are shared with Paddle.com Market Limited, our Merchant of Record, solely to process your subscription payment, calculate applicable tax, and handle refunds. SlovX does not store your full card details — Paddle handles this directly.</li>
            <li>With sub-processors and infrastructure providers (hosting, database, AI model providers) strictly to operate the Service.</li>
            <li>With integrations you explicitly connect (e.g. your CRM, Google Workspace) — data flows to these tools based on your configuration and permission.</li>
            <li>Where required by law, legal process, or to protect the rights, safety, or property of SlovX, our customers, or the public.</li>
            <li>In connection with a merger, acquisition, or asset sale, subject to continued protection under an equivalent privacy policy.</li>
          </ul>
        </LegalSection>

        <LegalSection number={6} title="Data Security">
          <p>
            Data in transit between your systems, End-Users, and SlovX infrastructure is encrypted using industry-standard
            protocols (HTTPS/TLS). We apply reasonable administrative, technical, and organizational safeguards designed to
            protect information against unauthorized access, alteration, or loss. No method of transmission or storage is
            completely secure, and we cannot guarantee absolute security.
          </p>
        </LegalSection>

        <LegalSection number={7} title="End-User (Lead) Notice">
          <p>
            If you are messaging a business's WhatsApp number that uses Xavier, your messages are being processed by an
            automated AI system on that business's behalf, as described in this Policy. The business (our Customer) is
            responsible for the content and configuration of its own Company Configuration and for its own direct relationship
            with you as its customer or prospect. To stop automated messages from a specific business, reply "STOP" — this is
            honored automatically.
          </p>
        </LegalSection>

        <LegalSection number={8} title="Your Rights">
          <p>
            Depending on your jurisdiction, you may have the right to access, correct, export, or request deletion of your
            personal data, and to object to or restrict certain processing. To exercise these rights, contact us at{' '}
            <a href="mailto:privacy@slovx.com" className="text-brand-400 hover:text-brand-300">privacy@slovx.com</a>.
            We will respond within the timeframe required by applicable law.
          </p>
        </LegalSection>

        <LegalSection number={9} title="International Data Transfers">
          <p>
            Depending on your location and the infrastructure providers used, information may be processed in countries other
            than your own. Where required, we rely on appropriate legal mechanisms (such as standard contractual clauses) to
            safeguard cross-border transfers.
          </p>
        </LegalSection>

        <LegalSection number={10} title="Children's Privacy">
          <p>
            The Service is intended for business use and is not directed at individuals under the age of 18. We do not
            knowingly collect personal information from children.
          </p>
        </LegalSection>

        <LegalSection number={11} title="Changes to This Policy">
          <p>
            We may update this Privacy Policy from time to time. Material changes will be communicated via the dashboard or
            your account email at least 14 days before taking effect.
          </p>
        </LegalSection>

        <LegalSection number={12} title="Contact">
          <p>
            Questions about this Privacy Policy or data-related requests can be directed to{' '}
            <a href="mailto:privacy@slovx.com" className="text-brand-400 hover:text-brand-300">privacy@slovx.com</a>.
            For payment or billing data questions specifically, contact{' '}
            <a href="mailto:billing@slovx.com" className="text-brand-400 hover:text-brand-300">billing@slovx.com</a>.
          </p>
        </LegalSection>
      </LegalDoc>
      <FooterMini />
    </>
  );
}
