// CSV + PDF export for leads and conversations.
// CSV is generated by hand (no deps). PDF uses `pdfkit`, a dependency-free layout engine.

import PDFDocument from 'pdfkit';
import { db } from '../config/database.js';

// ─── CSV helpers ─────────────────────────────────────────────

// Escape a cell so commas, quotes, and newlines don't break the CSV.
const csvCell = (v) => {
  if (v == null) return '';
  const s = String(v);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
};

const toCsv = (headers, rows) => {
  const headerRow = headers.map(csvCell).join(',');
  const bodyRows  = rows.map((r) => r.map(csvCell).join(','));
  return [headerRow, ...bodyRows].join('\r\n');
};

// ─── Leads exports ───────────────────────────────────────────

export const exportLeadsCsv = async (subscriberId) => {
  const leads = await db.lead.findMany({
    where:   { subscriberId },
    orderBy: { updatedAt: 'desc' },
    select: {
      customerName: true, customerPhone: true, email: true,
      status: true, sentiment: true, buyingIntent: true,
      optedOut: true, createdAt: true, updatedAt: true,
    },
  });

  const rows = leads.map((l) => [
    l.customerName ?? '',
    l.customerPhone,
    l.email ?? '',
    l.status,
    l.sentiment != null ? l.sentiment.toFixed(2) : '',
    l.buyingIntent != null ? l.buyingIntent.toFixed(2) : '',
    l.optedOut ? 'YES' : 'NO',
    l.createdAt.toISOString(),
    l.updatedAt.toISOString(),
  ]);

  return toCsv(
    ['Name', 'Phone', 'Email', 'Status', 'Sentiment', 'BuyingIntent', 'OptedOut', 'Created', 'Updated'],
    rows,
  );
};

// ─── Conversations exports ───────────────────────────────────

export const exportConversationsCsv = async (subscriberId) => {
  const convos = await db.conversation.findMany({
    where:   { subscriberId },
    orderBy: { updatedAt: 'desc' },
    select: {
      customerPhone: true, stage: true, messages: true, updatedAt: true,
      lead: { select: { customerName: true, status: true } },
    },
  });

  const rows = convos.map((c) => {
    const msgs = Array.isArray(c.messages) ? c.messages : [];
    const last = msgs[msgs.length - 1];
    return [
      c.lead?.customerName ?? '',
      c.customerPhone,
      c.lead?.status ?? '',
      c.stage,
      msgs.length,
      last?.content ?? '',
      c.updatedAt.toISOString(),
    ];
  });

  return toCsv(
    ['Name', 'Phone', 'LeadStatus', 'ConversationStage', 'MessageCount', 'LastMessage', 'Updated'],
    rows,
  );
};

// ─── PDF (leads summary) ─────────────────────────────────────
//
// Returns a Promise<Buffer> — controller pipes it to the HTTP response.

export const exportLeadsPdf = async (subscriberId) =>
  new Promise((resolve, reject) => {
    (async () => {
      try {
        const [leads, config] = await Promise.all([
          db.lead.findMany({
            where:   { subscriberId },
            orderBy: { updatedAt: 'desc' },
            take:    500, // hard cap so a huge account doesn't crash the export
            select: {
              customerName: true, customerPhone: true, status: true,
              sentiment: true, buyingIntent: true, updatedAt: true,
            },
          }),
          db.businessConfig.findUnique({
            where:  { subscriberId },
            select: { companyName: true },
          }),
        ]);

        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        const chunks = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end',  () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(18).text('Leads Report', { align: 'left' });
        doc.moveDown(0.2);
        doc.fontSize(10).fillColor('#666')
          .text(config?.companyName ?? 'Xavier account')
          .text(`Generated ${new Date().toLocaleString()}`)
          .text(`${leads.length} lead(s)${leads.length === 500 ? ' (showing first 500)' : ''}`);
        doc.moveDown(0.8);
        doc.fillColor('black');

        // Table header
        const startY = doc.y;
        const cols = [
          { label: 'Name',      x: 40,  w: 130 },
          { label: 'Phone',     x: 170, w: 100 },
          { label: 'Status',    x: 270, w: 80  },
          { label: 'Sentiment', x: 350, w: 70  },
          { label: 'Intent',    x: 420, w: 60  },
          { label: 'Updated',   x: 480, w: 80  },
        ];
        doc.fontSize(9).font('Helvetica-Bold');
        cols.forEach((c) => doc.text(c.label, c.x, startY, { width: c.w }));
        doc.moveDown(0.3);
        doc.font('Helvetica');
        doc.moveTo(40, doc.y).lineTo(555, doc.y).strokeColor('#ccc').stroke();
        doc.moveDown(0.3);

        // Rows
        for (const l of leads) {
          if (doc.y > 780) {
            doc.addPage();
          }
          const y = doc.y;
          const values = [
            l.customerName ?? 'Unknown',
            l.customerPhone,
            l.status,
            l.sentiment != null ? (l.sentiment * 10).toFixed(1) : '—',
            l.buyingIntent != null ? (l.buyingIntent * 10).toFixed(1) : '—',
            new Date(l.updatedAt).toLocaleDateString(),
          ];
          cols.forEach((c, i) => doc.text(values[i], c.x, y, { width: c.w, ellipsis: true }));
          doc.moveDown(0.3);
        }

        doc.end();
      } catch (err) {
        reject(err);
      }
    })();
  });
